### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by michaeldim** [lvcn1/ws-client-examples#10]
Periodically I am getting a 400 error responses from the server:

`WsResponseMetaData { responseType: 7 } ErrorResponse { code: 400, message: 'Unknown command' }`

As I am making multiple requests I cannot determine which request is causing this response and why it would respond with this error.  Is there any more information on why 'Unknown command' would be returned and what does it mean?

Also would you be able to provide a list of error codes and their descriptions that could be returned. 

Thanks

**Comment by michaeldim** [comment]
I am guessing from my testing there is more granular rate limits imposed and this error appears to be thrown when x commands per/second is exceeded?

**Comment by dkpostwww** [comment]
No, it is our error, it happens when message is not 'strict' (when it is streamed). This happens more often when you send messages fast. We are fixing this bug right now.

**Comment by michaeldim** [comment]
Ok thanks.  I have also noticed when I have sent a burst of orders, although they appear on the platform when I make a ClientOrdersRequest and loop through orderStatus.OPEN orders they are not returned in the request.

**Comment by michaeldim** [comment]
Its ok, the orders were in different row of data not returned with the parameters I had set in the request.

**Comment by dkpostwww** [comment]
Yesterday we've fixed issue with unexpected error 400 and updated the service. Is it ok now?

**Comment by michaeldim** [comment]
It appear so. However I am now getting a 419 error on a ClientOrdersRequest :
`{"code":409,"message":"client orders request error: 500 Internal Server Error}`
