### ISSUE TITLE
Balance via WS

### ISSUE THREAD

**Issue by SergeevGregory** [lvcn1/ws-client-examples#11]
Dear developers,
I try to get balances via WS (After successful login event - OK). I use C# sample as base of my test program.
Here my code:       
```
private void WsClient_GetBalances(int ttl)
        {
            byte[] msg;

            protobuf.ws.BalancesRequest message = new protobuf.ws.BalancesRequest
            {
                ExpireControl = new protobuf.ws.RequestExpired
                {
                    Now = (long)(DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds,
                    Ttl = ttl
                },
            };

            using (MemoryStream msgStream = new MemoryStream())
            {
                ProtoBuf.Serializer.Serialize(msgStream, message);
                msg = msgStream.ToArray();
            }

            byte[] sign = ComputeHash(MY_SECRET_KEY, msg);
            var meta = new protobuf.ws.WsRequestMetaData
            {
                RequestType = protobuf.ws.WsRequestMetaData.WsRequestMsgType.Balances,
                Token = "Balances",
                Sign = sign
            };

            protobuf.ws.WsRequest request = new protobuf.ws.WsRequest
            {
                Meta = meta,
                Msg = msg
            };

            sendRequest(request);
        }
```
I always get error: _Token:"Balances", Error code: "409", message:"balances request error: 400 Bad Request"_
Can you help me with this issue?

P.S. Also from time to time I get bad signature issue of my PlaceLimitOrder request

**Comment by dkpostwww** [comment]
If your bot 'hash' is 593ae0e5099708f4cb43d64e75bd7d91, you use API key with dasabled 'payments' api, so you cannot query balance.
If it is not your hash - check your api key, is it allowed to use payment api for it?

**Comment by dkpostwww** [comment]
Can you provide exact error code and error message?

**Comment by SergeevGregory** [comment]
Now I can't catch this error. May be it occurred because I put limit order before get login confirmation. I will overwatch for this. If this error occur again, I will write here.
