### ISSUE TITLE
PRIVATE_TRADE_NOTIFY missing

### ISSUE THREAD

**Issue by cymp** [lvcn1/ws-client-examples#14]
Dear Livecoin team,

I never receive any PRIVATE_TRADE_NOTIFY response whatever trade I successfully achieve, even though I subscribed to PrivateSubscribeTradeChannelRequest (I'm sure I do because I successufully receive a PRIVATE_TRADE_CHANNEL_SUBSCRIBED). Is this a known issue or do I do anything wrong?

**Comment by dkpostwww** [comment]
Seems like fixed. Can you confirm?
