### ISSUE TITLE
Tracking a placed order

### ISSUE THREAD

**Issue by cymp** [lvcn1/ws-client-examples#15]
Dear Livecoin team,

Whenever I am placing an order, I would like to track if the placing was successful or not. How can I do that, given the fact that I don't specify any request id when I am placing it? I am thinking about the case where I am sending several orders at almost the same time (because of concurrency), I am not guaranteed that the PUT_LIMIT_ORDER_RESPONSE I receive will arrive in a determined order. 

A solution for example would be that I would be able to specify a request id in my PutLimitOrderRequest, this way I would read the request id in a received PUT_LIMIT_ORDER_RESPONSE and be able to track my order.

My workaround for now is to wait for the PUT_LIMIT_ORDER_RESPONSE  to arrive whenever I am placing an order, queueing my other trades...

**Comment by michaeldim** [comment]
I put my own generated clientIds and order type in the token message as a string such as 'sendOrder MErM685pk' then when I get a message I can handle it accordingly.

**Comment by cymp** [comment]
Good advice thanks!
