### ISSUE TITLE
Private Order Notify

### ISSUE THREAD

**Issue by pivolan** [lvcn1/ws-client-examples#20]
Происходит путаница при получении следующих уведомлений:
1. Ордер был куплен, приходит quantity = 0, при этом в канал об ордерах информация приходит раньше чем в трейдинг.
2. Ордер был отменен, приходит так же quantity = 0.
3. Ордер был куплен при попытке отмены, приходит так же quantity = 0.
Добавьте пожалуйста статус ордера, т.к. приходится обрабатывать косвенные признаки,  хранить историю сообщений и ставить таймауты.
Т.е. чтобы выяснить что ордер был исполнен или отменен при получении order private notify quantity == 0, необходимо дождаться сообщения trade private notify, и потом сделать точный вывод, или убедиться что по таймауту сообщения не было, но таймаут - не надежно, время может меняться, и следующее сообщение может вообще не прийти из-за ошибок.

Спасибо.

**Comment by TriAnMan** [comment]
Да, вообще странная реализация каналов PRIVATE_SUBSCRIBE_ORDER_RAW и PRIVATE_SUBSCRIBE_TRADE.
Почему нельзя было отвечать в формате message Order или message ClientOrderResponse?
Еще и оба эти формата друг друга частично дублируют...

**Comment by dkpostwww** [comment]
2pivolan:
Если в PrivateOrderRawEvent добавить quantityLeftBeforeCancellation - этого хватит?
PS изначально планировалось, что будет ожидание ответа от cancelOrder, там есть информация "сколько осталось".

2TriAnMan:
Если чисто академически интерес - формат Order/ClientOrderResponse - калька с rest api чтобы проще было с этого rest переходить.
А так они слишком "жирные".

**Comment by pivolan** [comment]
Да quantityLeft будет достаточно. 
А по поводу сходства с rest, это никак не помогло мне, потому что разница между прототипом и рест json слишком большая и прослойка все равно написана. 
Спасибо за ответ

**Comment by TriAnMan** [comment]
@dkpostwww спасибо за ответ, но мне кажется, что некоторая избыточность в угоду удобства использования может быть выгодна. Например если она позволяет избежать дополнительных запросов или подписок. С точки зрения нагрузки на сеть пара дополнительных полей в ProtoBuff незначительны по сравнению с отправкой дополнительного уведомления. С точки зрения вычислительной нагрузки - возможны нюансы, но скорее всего то же самое.

С другой стороны ясное взаимодействие с API (например где клиентам не придется "догадываться" о том, что же произошло, а это сразу понятно исходя из уведомления), поможет привлечь больше пользователей этого API, что как мне кажется выгодно с точки зрения бизнеса.

Да, к сожалению, предположение о том что похожесть WS API на REST API поможет перейти на веб-сокеты для меня тоже не очень верно. По сути вместо модели Request-Response мы переходим на что-то типа Publisher-Subscriber. В результате весь код, который связан с отправкой и получением данных будет переписан почти с нуля. А вот ответ в формате Order/ClientOrderResponse помог бы мне избежать написания новой логики в **обработке изменения** состояния ордеров.

**Comment by dkpostwww** [comment]
На самом деле, вы, конечно, правы и все понятно.
Смущает только то, что изначально практически не было запросов о том, что чего-то не хватает для счастья.
PS PrivateOrderRawEvent.quantity_left_before_cancellation и .is_market появились

**Comment by TriAnMan** [comment]
К сожалению, возможность перейти на веб-сокеты у меня появилась только сейчас.
Начал знакомиться с API, чтобы понять как это реализовать и появились вопросы.

Да, кстати, файлик proto/LivecoinWSapi.proto несколько рассинхронизовался с файлами протокола из библиотек. А вижу, уже пофиксили. (: 👍
