### ISSUE TITLE
Occasional slow responses from websocket API

### ISSUE THREAD

**Issue by jsveto** [lvcn1/ws-client-examples#21]
I am experiencing slow responses from websocket API. When doing putLimitOrderRequest, usually responses from server are very fast (250ms), but sometimes responses are very slow (up to 10s and even more). My network connection is stable.

This does not effect REST API requests.

I have tested this from several Locations with several different websocket implementations. Is anyone else having same problem? 

I have opened support ticket nearly 2 weeks ago, but so far, nothing helpful.

Regards,
jsveto

**Comment by jsveto** [comment]
Additional info:
When slow responses happen, ping to ws.api.livecoin.net is OK/fast.

**Comment by dkpostwww** [comment]
There was an update at 17.11, we think this issue is closed.
Please, if this happens again, can you provide an exact time \ order id?
PS you can use PingRequest now to test "full network ping".

**Comment by pivolan** [comment]
All is ok now

**Comment by jsveto** [comment]
I think this issue can be closed for now. Thank you and keep up the good work!
