### ISSUE TITLE
PingRequest

### ISSUE THREAD

**Issue by pivolan** [lvcn1/ws-client-examples#23]
Как работает PingRequest, занимает ли он у вас время для обработки? Или это исключительно время задержки?
Если я делаю запрос с севрера который находится близко к вам по ip, то получаю задержку 140мс, при этом консольный ping ws.api.livecoin.net занимается всего 1мс до одного ip и 3мс до другово ip.
До этого ip  176.9.111.38 пинг 1мс
до этого ip 213.239.221.44 пинг 3мс
а через сокеты 140мс. И скорость создания ордера 140мс.
Получается это прокси антидддос сервера, сама обработка сокетов где-то далеко?
А есть что-то поближе?

**Comment by dkpostwww** [comment]
Добрый день.
Смысл PingRequest как раз в том, что время на его обработку не затрачивается - он сразу создает ответ с текущим серверным временем (чтобы можно было оценить разницу между in и out задержкой). Так что - да, именно время сетевой задержки.

> консольный ping ws.api.livecoin.net занимается всего 1мс. Получается это прокси антидддос сервера, сама обработка сокетов где-то далеко?
Да, именно так, сам кластер биржи не там.

> А есть что-то поближе?
Увы :(

**Comment by pivolan** [comment]
Получается если исключить задержки то время создания ордера у вас очень маленькое, примерно 14мс, верно? 
Похоже у вас там засланный казачок. Т.к. такие ордера и их исполнения очень часто случаются.

**Comment by dkpostwww** [comment]
Добрый день.
Ордера создаются существенно быстрей, чем 14мс.
Вот только что попробовал проверить:

def onSuccessfullLogin(token):
    putLimitOrder("HST/BTC",False,10, 0.000039)
    putLimitOrder("HST/BTC",True, 10, 0.000039)

в итоге разница между ордерами (если ведете запись торгов - id: 27735131301, 27735131251) - "0 years 0 mons 0 days 0 hours 0 mins 0.001055 secs".

Если бы кто-то продавал с кластера биржи, и ждал ответов - тоже явно меньше 14мс было бы. Да и засветился бы этот "кто-то" моментально.

По поводу случаев из вашего тикета - расследование проводилось, запросы прошли весь стандартный путь через прокси.

Ботоводов много, кто и зачем так торгует, с ваших слов "выжидая 14мс" - интересная загадка. Стратегия это какая-то хитрая, или руки у кого-то не оттуда растут - неизвестно. Но вы легко можете подобное повторить - просто добавьте в представленный кусочек кода time.sleep(0.013) ;)

**Comment by pivolan** [comment]
Получается обе транзакции были от одного аккаунта?
Почему вы сами не делаете таких транзакций? Ведь доход от арбитража значительно выше чем комиссия полученная с нас. И почему то ни одна биржа этого не делает. Есть какое-то не гласное правило?

**Comment by dkpostwww** [comment]
Обе сделки из вашего тикета были "сам у себя".

Почему мы сами не арбитражим стаканы? Потому, что в большом мире биржа и сотрудники НЕ имеют права быть участником торгов - это неравные возможности и инсайд, правило закреплено законодательно.  Ну и все стараются соответствовать.

Если бы биржа занималась арбитражом, доход на ней получить было бы "в принципе" невозможно, такая биржа никому не нужна.

**Comment by pivolan** [comment]
Спасибо!
