### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by cymp** [lvcn1/ws-client-examples#3]
Hello,

I can't seen any place in the documentation about these topics:
- How long does the connection lasts?
- Do we need to send a periodical ping to keep the connection alive?
- Are all of the subscriptions valid until the connection is closed?
- Is there a maximum number of subscriptions?

Feel free to close this topic when you update the documentation regarding these questions.

**Comment by dkpostwww** [comment]
[commit](https://github.com/lvcn1/ws-client-examples/commit/37bce094dd119124e3a1df198559e819474ccb3e)
