### ISSUE TITLE
No current orderbook state

### ISSUE THREAD

**Issue by sandybradley** [lvcn1/ws-client-examples#4]
Dear Livecoin community,

Upon testing your example js script, I receive updates for the subscribed orderbook but no snapshot of the current state as indicated in the documentation, which makes the updates useless.

Can anyone shed some light?

Faithfully,

Alexander

**Comment by dkpostwww** [comment]
Hello.
Can you provide log of your communication (text of your subscription request and the serve's answer)? Snapshot has to be in server's answer.

**Comment by sandybradley** [comment]
Dear DK,

Thank you for your response.

Here is my code for subscription ...

var socket = connect("wss://ws.api.livecoin.net/ws/beta");

    function onOrderBook(event) {
        // console.log("orderbook: " + JSON.stringify(event))
        let sym = event.channelId.split("_")[0];
        sym = sym.split("/")[0]+sym.split("/")[1];
        if(event.operation){
          // snapshot
          console.log("snapshot",sym,event.data);
        } else {
          console.log("update",sym,event);
        }

    }

    function onTrade(event) {
        console.log("trade: " + JSON.stringify(event))
    }

    function onError(event) {
        console.log("Server error: " + JSON.stringify(event))
    }

    function onSubscribe(channelId) {
        console.log("channel subscribed: " + channelId)
        //here you can make your trade decision
    }

    function onUnsubscribe(channelId) {
        console.log("channel unsubscribed: " + channelId)
        //here you can make your trade decision
    }

    function subscribe(params) {
        socket.send(JSON.stringify({"Subscribe":params}))
    }

    function unsubscribe(channelId) {
        socket.send(JSON.stringify({
            "Unsubscribe": {
                "channelId":channelId
            }
        }))
    }

    function connect(path) {
        return  new WebSocket(path);
    }

    function disconnect() {
        socket.close();
        console.log("Connection closed")
    }
    socket.onopen = function() {
        console.log("Connection established.");

        subscribe({
            "channelType": "orderbook",
            "symbol": "BTC/USD",
            "depth":20
        });
    };

    socket.onclose = function(event) {
        if (event.wasClean) {
            console.log('The connection is closed cleanly');
        } else {
            console.log('Connection failure'); // например, "убит" процесс
сервера
        }
        console.log('Code: ' + event.code + ' reason: ' + event.reason);
    };

    socket.onmessage = function(event) {
        // console.log("data received " + event.data);
        if(event.data !== '') {
            var msg = JSON.parse(event.data);
            var type;
            if (msg.hasOwnProperty('Error')) {
                onError(msg)
            } else if (msg.hasOwnProperty("operation")) {
                if (msg.operation.hasOwnProperty("Subscribe")) {
                    onSubscribe(msg.channelId);
                    if (msg.hasOwnProperty("data")) {
                        type = msg.channelId.split('_')[1];
                        msg.data.forEach(function (item) {
                            item.channelId = msg.channelId;
                            if (type === 'orderbook') {
                                onOrderBook(item)
                            }
                        })
                    }
                } else if (msg.operation.hasOwnProperty("Unsubscribe")) {
                    onUnsubscribe(msg.channelId)
                } else {
                    console.log("Unsupported operation")
                }
            } else {
                type = msg.channelId.split('_')[1];
                if (type === 'orderbook') {
                    onOrderBook(msg)
                } else if (type === 'trade') {
                    onTrade(msg)
                }
            }
        }
    };

    socket.onerror = function(error) {
        console.log("Websocket error " + error.message);
    };

And the result on the console ...

Connection established.
channel subscribed: BTC/USD_orderbook
update BTCUSD { price: -8192.01001,
  quantity: 0.0000336,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8222.99836,
  quantity: 0.00750669,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8222.99838,
  quantity: 0.0002269,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8223.2149,
  quantity: 0.03824735,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8224.11085,
  quantity: 0.00791,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8234.99996,
  quantity: 0.08363255,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8240,
  quantity: 0.08851,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8249,
  quantity: 0.02265375,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8249.99999,
  quantity: 0.28376323,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8250,
  quantity: 0.14472066,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8250.18817,
  quantity: 0.00072926,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8254.20173,
  quantity: 0.02163,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8258,
  quantity: 0.02121864,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8259,
  quantity: 0.4142,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8261.1135,
  quantity: 0.00315957,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8268,
  quantity: 0.0103,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8270, quantity: 0.02, channelId:
'BTC/USD_orderbook' }
update BTCUSD { price: -8275.99999,
  quantity: 0.00576142,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8277,
  quantity: 0.06429504,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: -8277.35259,
  quantity: 0.04415532,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8192.00001,
  quantity: 0.00788189,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8192,
  quantity: 0.17081643,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8191.03005,
  quantity: 0.02073481,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8187,
  quantity: 0.00407,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8178.1,
  quantity: 0.05261,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8178.05,
  quantity: 0.04577,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8175,
  quantity: 0.00305,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8170,
  quantity: 0.00305,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8165.00002,
  quantity: 0.02336,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8165,
  quantity: 0.00305,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8156.16,
  quantity: 0.0996,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8155.39581,
  quantity: 0.35346954,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8155,
  quantity: 0.00306,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8153.86199,
  quantity: 0.0033,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8151.05,
  quantity: 0.00046,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8137.55426,
  quantity: 0.00331,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8130.5052,
  quantity: 0.00303691,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8130,
  quantity: 0.00491,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8121.27915,
  quantity: 0.00332,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { price: 8120.54104,
  quantity: 0.00042,
  channelId: 'BTC/USD_orderbook' }
update BTCUSD { channelId: 'BTC/USD_orderbook',
  price: -9844.68227,
  quantity: 0.05331587 }

**Comment by dkpostwww** [comment]
Here is the communication log:
Request: {"Subscribe":{"channelType": "orderbook","symbol": "BTC/USD","depth":20}}
Response: {"channelId":"BTC/USD_orderbook","operation":{"Subscribe":{"channelType":"orderbook","symbol":"BTC/USD","depth":20}},"data":[{"price":-8233.99996,"quantity":0.0118165},{"price":-8233.99997,"quantity":0.00248759},{"price":-8233.99998,"quantity":0.00214699},{"price":-8234,"quantity":0.02121864},{"price":-8234.99986,"quantity":0.00480428},{"price":-8244.11085,"quantity":0.00701244},...

So, 

if (msg.operation.hasOwnProperty("Subscribe")) {
                    onSubscribe(msg.channelId);
                    if (msg.hasOwnProperty("data")) {
                        type = msg.channelId.split('_')[1];
                        msg.data.forEach(function (item) {
                            item.channelId = msg.channelId;
                            if (type === 'orderbook') {
                                onOrderBook(item)
                            }
                        })
                    }

IMHO, should looks like this:

if (msg.operation.hasOwnProperty("Subscribe")) {
                    onSubscribe(msg.channelId);
                    if (msg. **operation.** hasOwnProperty("data")) {
                        type = msg.channelId.split('_')[1];
                        msg. **operation.** data.forEach(function (item) {
                            item.channelId = msg.channelId;
                            if (type === 'orderbook') {
                                onOrderBook(item)
                            }
                        })
                    }

or better wait 1-2 days and get start with 
https://github.com/lvcn1/ws-client-examples/tree/beta_v2

Current ws-api will be obsolete (and closed in 2-maybe more months), new api will be strong-typed, faster and richer ;). New api will be available this week.

**Comment by dkpostwww** [comment]
Sorry, my code in previous comment also will not work. But snapshot is really given by server, you can see it if you will log entire messages to console...

**Comment by sandybradley** [comment]
Thank you. I'll make some changes to my code, as you suggested and keep an
eye out for the new api.
