### ISSUE TITLE
websocket private API not working anymore

### ISSUE THREAD

**Issue by jsveto** [lvcn1/ws-client-examples#8]
Hi, since 25. August from around 2AM server time, my bot is unable to perform private API requests on websocket. Server does not respond to login/putLimitOrder requests anymore (I did not change my code).

I tried to issue new API key, but still no luck. private requests do work OK when using old REST API.

Is this known issue?

**Comment by michaeldim** [comment]
I am experiencing same issue

**Comment by Cashik** [comment]
I just started learning the WS API. Python examples from the repository work only for public methods and do not work for private (for my keys).

**Comment by velorias** [comment]
Same problem. And in python version too.

**Comment by dkpostwww** [comment]
Sorry, fixed. We are working to ensure that this does not happen again.
